GET http://localhost:8080/mvc_framework/Db/Find/1

###
POST http://localhost:8080/mvc_framework/Db/Find/1

###
PATCH http://localhost:8080/mvc_framework/File/
Content-Type: application/json

{
    
}
